# Generated by Django 3.2 on 2021-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='situacao',
            field=models.CharField(choices=[('PRO', 'processando_autorizacao'), ('AUT', 'autorizado'), ('CAN', 'cancelado'), ('ERR', 'erro_autorizacao'), ('DEN', 'denegado')], max_length=3, verbose_name='Situação'),
        ),
    ]
