# Generated by Django 3.2 on 2021-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0002_alter_nfe_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe',
            name='situacao',
        ),
        migrations.AddField(
            model_name='nfe',
            name='status_nfe',
            field=models.CharField(choices=[('PRO', 'processando_autorizacao'), ('AUT', 'autorizado'), ('CAN', 'cancelado'), ('ERR', 'erro_autorizacao'), ('DEN', 'denegado')], default='ERR', max_length=3, verbose_name='Status NFe'),
            preserve_default=False,
        ),
    ]
