# Generated by Django 3.2 on 2021-05-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0003_auto_20210501_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfe',
            old_name='emitente_id',
            new_name='emitente',
        ),
    ]
