# Generated by Django 3.2 on 2021-04-23 19:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import emitentes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=40)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(max_length=60)),
                ('municipio', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('telefones', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('certificado_a1', models.FileField(blank=True, null=True, upload_to=emitentes.models.emitente_upload_file)),
                ('logotipo_dfe', models.ImageField(blank=True, null=True, upload_to=emitentes.models.emitente_upload_file)),
                ('nfe_emite', models.BooleanField(default=False, verbose_name='Emite NFe')),
                ('nfe_serie', models.IntegerField(default=0, verbose_name='Série NFe')),
                ('nfe_numero', models.IntegerField(default=0, verbose_name='Número NFe')),
                ('nfe_serie_homologacao', models.IntegerField(default=0, verbose_name='Série NFe em homologação')),
                ('nfe_numero_homologacao', models.IntegerField(default=0, verbose_name='Número NFe em homologação')),
                ('nfce_emite', models.BooleanField(default=False, verbose_name='Emite NFCe')),
                ('nfce_serie', models.IntegerField(default=0, verbose_name='Série NFCe')),
                ('nfce_numero', models.IntegerField(default=0, verbose_name='Número NFCe')),
                ('nfce_serie_homologacao', models.IntegerField(default=0, verbose_name='Série NFCe em homologação')),
                ('nfce_numero_homologacao', models.IntegerField(default=0, verbose_name='Número NFCe em homologação')),
                ('cte_emite', models.BooleanField(default=False, verbose_name='Emite CTe')),
                ('cte_serie', models.IntegerField(default=0, verbose_name='Série CTe')),
                ('cte_numero', models.IntegerField(default=0, verbose_name='Número CTe')),
                ('cte_serie_homologacao', models.IntegerField(default=0, verbose_name='Série CTe')),
                ('cte_numero_homologacao', models.IntegerField(default=0, verbose_name='Número CTe em homologação')),
                ('mdfe_emite', models.BooleanField(default=False, verbose_name='Emite MDFe')),
                ('mdfe_serie', models.IntegerField(default=0, verbose_name='Série MDFe')),
                ('mdfe_numero', models.IntegerField(default=0, verbose_name='Número MDFe')),
                ('mdfe_serie_homologacao', models.IntegerField(default=0, verbose_name='Série MDFe em homologação')),
                ('mdfe_numero_homologacao', models.IntegerField(default=0, verbose_name='Número MDFe em homologação')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requests_credit', models.IntegerField(default=100, verbose_name='Crédito Requisições')),
                ('requests_timer', models.IntegerField(default=0, verbose_name='Cronômetro de Requisições')),
                ('emissoes_suspensas', models.BooleanField(default=False, verbose_name='Suspender Emissões')),
                ('is_active', models.BooleanField(default=True, help_text='Emitentes inativos não aparecem no sistema (api)', verbose_name='Emitente Ativo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Cadastrado Em')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
