# Generated by Django 3.2 on 2021-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emitente',
            name='token',
        ),
        migrations.AddField(
            model_name='emitente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado Em'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='requests_timer',
            field=models.IntegerField(default=0, help_text='Limite de 60 segundos para até 100 solicitações', verbose_name='Cronômetro de Requisições'),
        ),
    ]
