# Generated by Django 3.2 on 2021-04-21 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitente',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
