# Generated by Django 3.2 on 2021-05-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0002_auto_20210501_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emitente',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='emitente',
            name='certificado_pw',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha do Certificado'),
        ),
        migrations.AddField(
            model_name='emitente',
            name='certificado_validade',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validade do Certificado'),
        ),
    ]
