# Generated by Django 3.2 on 2021-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0002_emitente_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emitente',
            old_name='cte_status',
            new_name='cte_emite',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='emitente_status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='mdfe_status',
            new_name='mdfe_emite',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='nfce_status',
            new_name='nfce_emite',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='nfe_status',
            new_name='nfe_emite',
        ),
        migrations.RemoveField(
            model_name='emitente',
            name='emissoes_status',
        ),
        migrations.AddField(
            model_name='emitente',
            name='emissoes_suspensas',
            field=models.BooleanField(default=False, verbose_name='Suspender Emissões'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Cadastrado Em'),
        ),
    ]
