# Generated by Django 3.2 on 2021-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0003_auto_20210421_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Emitentes inativos não aparecem no sistema (api)', verbose_name='Emitente Ativo'),
        ),
    ]
