# Generated by Django 3.2 on 2021-05-03 19:17

from django.db import migrations, models
import emitentes.models


class Migration(migrations.Migration):

    dependencies = [
        ('emitentes', '0003_auto_20210502_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitente',
            name='certificado_validade',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Validade do Certificado'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Emitentes inativos não tem acesso a API', verbose_name='Emitente Ativo'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='logotipo_dfe',
            field=models.ImageField(blank=True, null=True, upload_to=emitentes.models.emitente_upload_file, verbose_name='Logotipo DFe'),
        ),
    ]
