# Generated by Django 3.2 on 2021-04-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emitentes', '0004_alter_emitente_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitente',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
