# Generated by Django 3.2 on 2021-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=14)),
                ('inscricao_estadual', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=11)),
                ('cob_logradouro', models.CharField(max_length=60)),
                ('cob_numero', models.CharField(max_length=40)),
                ('cob_complemento', models.CharField(max_length=60)),
                ('cob_bairro', models.CharField(max_length=60)),
                ('cob_municipio', models.CharField(max_length=60)),
                ('cob_uf', models.CharField(max_length=2)),
                ('cob_cep', models.CharField(max_length=8)),
                ('cob_fones', models.CharField(max_length=60)),
                ('nfe', models.BooleanField(default=False)),
                ('nfce', models.BooleanField(default=False)),
                ('cte', models.BooleanField(default=False)),
                ('mdfe', models.BooleanField(default=False)),
                ('emissoes_ativo', models.BooleanField(default=False)),
                ('cadastro_ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
