# Generated by Django 3.2 on 2021-04-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitente',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
