# Generated by Django 3.2 on 2021-04-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitente', '0005_alter_emitente_cobranca_complemento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_cep',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_complemento',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_logradouro',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_municipio',
            new_name='municipio',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_fones',
            new_name='telefones',
        ),
        migrations.RenameField(
            model_name='emitente',
            old_name='cobranca_uf',
            new_name='uf',
        ),
    ]
