# Generated by Django 3.2 on 2021-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitente', '0006_auto_20210412_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitente',
            name='cadastro_ativo',
            field=models.BooleanField(default=True, verbose_name='Cadastro Ativo'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='cte',
            field=models.BooleanField(default=False, verbose_name='CTe'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='emissoes_ativo',
            field=models.BooleanField(default=False, verbose_name='Emissões Ativas'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='mdfe',
            field=models.BooleanField(default=False, verbose_name='MDFe'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='nfce',
            field=models.BooleanField(default=False, verbose_name='NFCe'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='nfe',
            field=models.BooleanField(default=False, verbose_name='NFe'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
